DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS countries CASCADE;
DROP TABLE IF EXISTS people CASCADE;
DROP TABLE IF EXISTS in_game_roles CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS people_teams_roles CASCADE;
DROP TABLE IF EXISTS tournaments_teams CASCADE;
DROP TABLE IF EXISTS groups CASCADE;
DROP TYPE IF EXISTS person_status;